# Generated by Django 6.0.2 on 2026-02-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_roomtype_remove_project_category_project_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='room_types',
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
