# Generated by Django 6.0.2 on 2026-02-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_project_room_types_delete_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='design_loc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.CharField(max_length=500),
        ),
    ]
