# Generated by Django 6.0.2 on 2026-02-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project_design_loc_alter_project_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contact_number',
            field=models.CharField(blank=True, default='+919109231207', max_length=20, null=True),
        ),
    ]
